export const movies = [
    { title: 'Вторая жизнь Уве', image: '/movie-suggester/images/1.jpg' },
    { title: 'Собачья жизнь', image: '/movie-suggester/images/2.jpg' },
    { title: 'Душа', image: '/movie-suggester/images/3.jpg' },
    { title: 'Сплит', image: '/movie-suggester/images/4.jpg' },
    { title: 'Энканто', image: '/movie-suggester/images/5.jpg' },
    { title: 'Из 13 в 30', image: '/movie-suggester/images/6.jpg' },
    { title: 'Отпетые мошенницы', image: '/movie-suggester/images/7.jpg' },
    { title: 'Она — мужчина', image: '/movie-suggester/images/8.jpg' },
    { title: 'Выпускной класс', image: '/movie-suggester/images/9.jpg' },
    { title: '8 подруг Оушена', image: '/movie-suggester/images/10.jpg' },
    { title: 'Келинка Сабина', image: '/movie-suggester/images/11.jpg' },
    { title: 'Лоракс', image: '/movie-suggester/images/12.jpg' },
    { title: 'Дом', image: '/movie-suggester/images/13.jpg' },
    { title: 'Высший пилотаж', image: '/movie-suggester/images/14.jpg' },
    { title: 'Митчеллы против машин', image: '/movie-suggester/images/15.jpg' },
    { title: 'Главный герой', image: '/movie-suggester/images/16.jpg' },
    { title: 'Эмоджи', image: '/movie-suggester/images/17.jpg' },
    { title: 'Ральф', image: '/movie-suggester/images/18.jpg' },
    { title: 'Неисправимый Рон', image: '/movie-suggester/images/19.jpg' },
    { title: 'Лови волну', image: '/movie-suggester/images/20.jpg' },
    { title: 'Мелкая', image: '/movie-suggester/images/21.jpg' },
    { title: 'Яна и Янко', image: '/movie-suggester/images/22.jpg' },
    { title: 'Чумовая пятница', image: '/movie-suggester/images/23.jpg' },
];
