export const movies = [
  { title: "Собачья жизнь", image: "./images/2.jpg" },
  { title: "Душа", image: "./images/3.jpg" },
  { title: "Сплит", image: "./images/4.jpg" },
  { title: "Энканто", image: "./images/5.jpg" },
  { title: "Из 13 в 30", image: "./images/6.jpg" },
  { title: "Отпетые мошенницы", image: "./images/7.jpg" },
  { title: "Она - мужчина", image: "./images/8.jpg" },
  { title: "Выпускной класс", image: "./images/9.jpg" },
  { title: "8 подруг Оушена", image: "./images/10.jpg" },
  { title: "Келинка Сабина", image: "./images/11.jpg" },
  { title: "Лоракс", image: "./images/12.jpg" },
  { title: "Дом", image: "./images/13.jpg" },
  { title: "Высший пилотаж", image: "./images/14.jpg" },
  { title: "Митчеллы против машин", image: "./images/15.jpg" },
  { title: "Главный герой", image: "./images/16.jpg" },
  { title: "Эмоджи", image: "./images/17.jpg" },
  { title: "Ральф", image: "./images/18.jpg" },
  { title: "Неисправимый Рон", image: "./images/19.jpg" },
  { title: "Лови волну", image: "./images/20.jpg" },
  { title: "Мелкая", image: "./images/21.jpg" },
  { title: "Яна и Янко", image: "./images/22.jpg" },
  { title: "Чумовая пятница", image: "./images/23.jpg" }
]